name: xandr_ios
description: flutter plugin for the Xandr,
  with integrations for Android and iOS - iOS implementation
version: 0.3.0
homepage: https://github.com/thekorn/xandr
repository: https://github.com/thekorn/xandr
resolution: workspace

environment:
  sdk: "^3.9.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: xandr
    platforms:
      ios:
        pluginClass: XandrPlugin
        dartPluginClass: XandrIOS

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  xandr_platform_interface: ^0.3.0

dev_dependencies:
  build_runner: ^2.7.0
  flutter_test:
    sdk: flutter
  mockito: ^5.5.0
  pana: ^0.23.1
  pigeon: ">=25.3.0 <27.0.0"
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0
