name: xandr_ios
description: flutter plugin for the Xandr,
  with integrations for Android and iOS - iOS implementation
version: 0.2.5+2
homepage: https://github.com/thekorn/xandr
repository: https://github.com/thekorn/xandr

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: xandr
    platforms:
      ios:
        pluginClass: XandrPlugin
        dartPluginClass: XandrIOS

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  xandr_platform_interface: ^0.2.5+2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  pana: ^0.22.9
  pigeon: ^21.1.0
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
