name: xandr_android
description: flutter plugin for the Xandr,
  with integrations for Android and iOS - Android implementation
version: 0.2.3+9
homepage: https://github.com/thekorn/xandr
repository: https://github.com/thekorn/xandr


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: xandr
    platforms:
      android:
        package: de.thekorn.xandr
        pluginClass: XandrPlugin
        dartPluginClass: XandrAndroid

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  xandr_platform_interface: ^0.2.3+9

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  pana: ^0.22.0
  pigeon: ^21.0.0
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
