name: xandr
description: flutter plugin for the Xandr,
  with integrations for Android and iOS
version: 0.2.5+2
homepage: https://github.com/thekorn/xandr
repository: https://github.com/thekorn/xandr


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: xandr_android
      ios:
        default_package: xandr_ios

dependencies:
  flutter:
    sdk: flutter
  xandr_android: ^0.2.5+2
  xandr_ios: ^0.2.5+2
  xandr_platform_interface: ^0.2.5+2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.4
  pana: ^0.22.9
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
