name: xandr_platform_interface
description: flutter plugin for the Xandr,
  with integrations for Android and iOS - platform interface  
version: 0.2.3+13
homepage: https://github.com/thekorn/xandr
repository: https://github.com/thekorn/xandr


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  pana: ^0.22.0
  very_good_analysis: ^6.0.0
