name: xandr_platform_interface
description: flutter plugin for the Xandr,
  with integrations for Android and iOS - platform interface
version: 0.3.1
homepage: https://github.com/thekorn/xandr
repository: https://github.com/thekorn/xandr
resolution: workspace

environment:
  sdk: "^3.9.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  build_runner: ^2.7.0
  flutter_test:
    sdk: flutter
  mockito: ^5.5.0
  pana: ^0.23.1
  very_good_analysis: ^10.0.0
